import type { Open3dCatalogItem, Open3dCatalogCategory } from "../catalog/catalogTypes";
import { proofCatalogItem } from "../catalog/proofCatalog";

function createCatalogItemFromProof(proof: typeof proofCatalogItem): Open3dCatalogItem {
  return {
    id: proof.id,
    slug: proof.id,
    sku: `PROOF-${proof.id}`,
    name: proof.name,
    shortName: proof.name.slice(0, 30),
    description: `Proof item: ${proof.name}`,
    category: "Furniture" as Open3dCatalogCategory,
    subCategory: "Chairs",
    taxonomyPath: "Furniture > Chairs",
    dimensions: {
      widthMm: proof.widthMm,
      depthMm: proof.depthMm,
      heightMm: 800,
    },
    displayUnit: "mm",
    assets: {
      imageUrls: [],
      previewImageUrl: proof.previewUrl,
    },
    material: {
      marketingMaterial: "Default",
      normalizedMaterial: "default",
    },
    roomTags: ["Office"],
    styleTags: ["Modern"],
    availability: "in-stock",
    assemblyType: "fully-assembled",
    flatPack: false,
    tags: ["proof", "test"],
    variants: [],
    provenance: {
      source: "proof_catalog",
    },
    symbolOnly: false,
  };
}

/** Offline catalog seed used when the live API is unavailable. */
export const OPEN3D_DEMO_CATALOG_ITEMS: Open3dCatalogItem[] = [
  createCatalogItemFromProof(proofCatalogItem),
  {
    id: "sample-sofa-1",
    slug: "sample-sofa-1",
    sku: "SOFA-001",
    name: "Modern 3-Seater Sofa",
    shortName: "Modern 3-Seater Sofa",
    description: "A comfortable modern sofa",
    category: "Furniture",
    subCategory: "Sofas & Sectionals",
    taxonomyPath: "Furniture > Sofas & Sectionals",
    dimensions: { widthMm: 2200, depthMm: 900, heightMm: 850 },
    displayUnit: "mm",
    assets: { imageUrls: [], previewImageUrl: "/placeholder-sofa.svg" },
    material: { marketingMaterial: "Gray Fabric", normalizedMaterial: "fabric" },
    roomTags: ["Living Room"],
    styleTags: ["Modern", "Minimalist"],
    availability: "in-stock",
    assemblyType: "flat-pack",
    flatPack: true,
    tags: ["sofa", "fabric", "gray"],
    variants: [],
    provenance: { source: "sample_data" },
    symbolOnly: false,
  },
  {
    id: "sample-desk-1",
    slug: "sample-desk-1",
    sku: "DESK-001",
    name: "Executive Standing Desk",
    shortName: "Executive Standing Desk",
    description: "Height-adjustable standing desk",
    category: "Furniture",
    subCategory: "Desks & Workstations",
    taxonomyPath: "Furniture > Desks & Workstations",
    dimensions: { widthMm: 1600, depthMm: 800, heightMm: 1200 },
    displayUnit: "mm",
    assets: { imageUrls: [], previewImageUrl: "/placeholder-desk.svg" },
    material: { marketingMaterial: "White Oak", normalizedMaterial: "oak" },
    roomTags: ["Office"],
    styleTags: ["Modern", "Scandinavian"],
    availability: "in-stock",
    assemblyType: "flat-pack",
    flatPack: true,
    tags: ["desk", "standing", "oak"],
    variants: [],
    provenance: { source: "sample_data" },
    symbolOnly: false,
  },
  {
    id: "sample-chair-1",
    slug: "sample-chair-1",
    sku: "CHAIR-001",
    name: "Ergonomic Office Chair",
    shortName: "Ergonomic Office Chair",
    description: "Adjustable ergonomic chair with lumbar support",
    category: "Furniture",
    subCategory: "Chairs",
    taxonomyPath: "Furniture > Chairs",
    dimensions: { widthMm: 650, depthMm: 650, heightMm: 1100 },
    displayUnit: "mm",
    assets: { imageUrls: [], previewImageUrl: "/placeholder-chair.svg" },
    material: { marketingMaterial: "Black Mesh", normalizedMaterial: "mesh" },
    roomTags: ["Office"],
    styleTags: ["Modern"],
    availability: "in-stock",
    assemblyType: "flat-pack",
    flatPack: true,
    tags: ["chair", "office", "ergonomic"],
    variants: [],
    provenance: { source: "sample_data" },
    symbolOnly: false,
  },
];

export function getDemoCatalogItemById(id: string): Open3dCatalogItem | undefined {
  return OPEN3D_DEMO_CATALOG_ITEMS.find((item) => item.id === id);
}
