packages:
  - site
  - tech-docs-generator

overrides:
  lodash-es: 4.18.1
  postcss: 8.5.15
  '@excalidraw/excalidraw>nanoid': 3.3.15
  '@excalidraw/mermaid-to-excalidraw>nanoid': 5.0.9

allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  '@percy/core': false
  '@sentry/cli': true
  '@swc/core': true
  canvas: true
  core-js: true
  es5-ext: true
  esbuild: true
  protobufjs: false
  sharp: true
  unrs-resolver: true
  workerd: true
  ws: set this to true or false

minimumReleaseAgeExclude:
  - '@types/node@26.1.0'

onlyBuiltDependencies:
  - "@firebase/util"
  - "@parcel/watcher"
  - "@swc/core"
  - canvas
  - core-js
  - es5-ext
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

nodeLinker: hoisted
