// @vitest-environment node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const siteRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");

const scriptPath = path.join(siteRoot, "scripts/generate-contents-md.mjs");

function render({
  title,
  why,
  contains,
  rules,
  see,
}: {
  title: string;
  why: string;
  contains: string[];
  rules?: string[];
  see?: string[];
}) {
  const lines = [
    `# ${title}`,
    "",
    why,
    "",
    "## Contains",
    "",
    ...contains.map((c) => `- ${c}`),
  ];
  if (rules?.length) {
    lines.push("", "## Rules", "", ...rules.map((r) => `- ${r}`));
  }
  if (see?.length) {
    lines.push("", "## See also", "", ...see.map((s) => `- \`${s}\``));
  }
  lines.push(
    "",
    "---",
    "*Generated by `site/scripts/generate-contents-md.mjs` — edit manifest, then `pnpm run docs:sync:all` from repo root.*",
    "",
  );
  return lines.join("\n");
}

describe("generate-contents-md (name-mirror)", () => {
  it("writes CONTENTS.md from repo and site folder manifests", () => {
    const src = fs.readFileSync(scriptPath, "utf8");
    expect(src).toContain("CONTENTS.md");
    expect(src).toContain("repoFolders");
    expect(src).toContain("siteFolders");
    expect(src).toContain("writeContents");
    expect(src).toContain("generate-contents-md.mjs");
  });

  it("render builds markdown with contains rules and footer", () => {
    const md = render({
      title: "scripts",
      why: "Ops tooling.",
      contains: ["generate-docs.mjs"],
      rules: ["No secrets"],
      see: ["docs/"],
    });
    expect(md).toContain("# scripts");
    expect(md).toContain("- generate-docs.mjs");
    expect(md).toContain("## Rules");
    expect(md).toContain("- No secrets");
    expect(md).toContain("`docs/`");
    expect(md).toContain("Generated by");
  });
});
